apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
  namespace: hrubo
spec:
  containers:
  - image: hello-world
    name: hello-world
    resources: {}
  replicaset: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
